//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("RequestOrganisationRequestRequest", Namespace="", IsNullable=false)]
public partial class RequestOrganisationRequestType {
    
    private System.DateTime dateTimeField;
    
    private string administratorEmailAddressField;
    
    private string accountField;
    
    private string nameField;
    
    private string assumedNameField;
    
    private string address1Field;
    
    private string address2Field;
    
    private string localityField;
    
    private string stateField;
    
    private string postalCodeField;
    
    private string countryField;
    
    private string mainPhoneField;
    
    private string dUNSField;
    
    private string supportEmailField;
    
    private bool isEVField;
    
    private string registrationNumberField;
    
    private string eVCityField;
    
    private string eVStateField;
    
    private string eVCountryField;
    
    private string agencyField;
    
    private BusinessCategoryType businessCategoryField;
    
    private bool businessCategoryFieldSpecified;
    
    private int secretQuestionsField;
    
    private bool secretQuestionsFieldSpecified;
    
    private bool requiresCertificateAuthorisationSSLField;
    
    private bool requiresCertificateAuthorisationSSLFieldSpecified;
    
    private bool requiresCertificateAuthorisationEVField;
    
    private bool requiresCertificateAuthorisationEVFieldSpecified;
    
    private bool requiresCertificateAuthorisationEUField;
    
    private bool requiresCertificateAuthorisationEUFieldSpecified;
    
    private bool requiresCertificateRevocationAuthorisationField;
    
    private bool requiresCertificateRevocationAuthorisationFieldSpecified;
    
    private bool isSSLField;
    
    private bool isEndUserField;
    
    private bool testField;
    
    private bool testFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime DateTime {
        get {
            return this.dateTimeField;
        }
        set {
            this.dateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AdministratorEmailAddress {
        get {
            return this.administratorEmailAddressField;
        }
        set {
            this.administratorEmailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Account {
        get {
            return this.accountField;
        }
        set {
            this.accountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AssumedName {
        get {
            return this.assumedNameField;
        }
        set {
            this.assumedNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Locality {
        get {
            return this.localityField;
        }
        set {
            this.localityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PostalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MainPhone {
        get {
            return this.mainPhoneField;
        }
        set {
            this.mainPhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DUNS {
        get {
            return this.dUNSField;
        }
        set {
            this.dUNSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SupportEmail {
        get {
            return this.supportEmailField;
        }
        set {
            this.supportEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool IsEV {
        get {
            return this.isEVField;
        }
        set {
            this.isEVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RegistrationNumber {
        get {
            return this.registrationNumberField;
        }
        set {
            this.registrationNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EVCity {
        get {
            return this.eVCityField;
        }
        set {
            this.eVCityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EVState {
        get {
            return this.eVStateField;
        }
        set {
            this.eVStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EVCountry {
        get {
            return this.eVCountryField;
        }
        set {
            this.eVCountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Agency {
        get {
            return this.agencyField;
        }
        set {
            this.agencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public BusinessCategoryType BusinessCategory {
        get {
            return this.businessCategoryField;
        }
        set {
            this.businessCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BusinessCategorySpecified {
        get {
            return this.businessCategoryFieldSpecified;
        }
        set {
            this.businessCategoryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int SecretQuestions {
        get {
            return this.secretQuestionsField;
        }
        set {
            this.secretQuestionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SecretQuestionsSpecified {
        get {
            return this.secretQuestionsFieldSpecified;
        }
        set {
            this.secretQuestionsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool RequiresCertificateAuthorisationSSL {
        get {
            return this.requiresCertificateAuthorisationSSLField;
        }
        set {
            this.requiresCertificateAuthorisationSSLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiresCertificateAuthorisationSSLSpecified {
        get {
            return this.requiresCertificateAuthorisationSSLFieldSpecified;
        }
        set {
            this.requiresCertificateAuthorisationSSLFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool RequiresCertificateAuthorisationEV {
        get {
            return this.requiresCertificateAuthorisationEVField;
        }
        set {
            this.requiresCertificateAuthorisationEVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiresCertificateAuthorisationEVSpecified {
        get {
            return this.requiresCertificateAuthorisationEVFieldSpecified;
        }
        set {
            this.requiresCertificateAuthorisationEVFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool RequiresCertificateAuthorisationEU {
        get {
            return this.requiresCertificateAuthorisationEUField;
        }
        set {
            this.requiresCertificateAuthorisationEUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiresCertificateAuthorisationEUSpecified {
        get {
            return this.requiresCertificateAuthorisationEUFieldSpecified;
        }
        set {
            this.requiresCertificateAuthorisationEUFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool RequiresCertificateRevocationAuthorisation {
        get {
            return this.requiresCertificateRevocationAuthorisationField;
        }
        set {
            this.requiresCertificateRevocationAuthorisationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiresCertificateRevocationAuthorisationSpecified {
        get {
            return this.requiresCertificateRevocationAuthorisationFieldSpecified;
        }
        set {
            this.requiresCertificateRevocationAuthorisationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool IsSSL {
        get {
            return this.isSSLField;
        }
        set {
            this.isSSLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool IsEndUser {
        get {
            return this.isEndUserField;
        }
        set {
            this.isEndUserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool Test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TestSpecified {
        get {
            return this.testFieldSpecified;
        }
        set {
            this.testFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
[System.SerializableAttribute()]
public enum BusinessCategoryType {
    
    /// <remarks/>
    privateOrganisation,
    
    /// <remarks/>
    governmentEntity,
    
    /// <remarks/>
    businessEntity,
    
    /// <remarks/>
    nonCommercialEntity,
}
