//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Keyfactor.AnyGateway.Quovadis.Client.XSDs
{
    // 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlRoot("RequestSSLCertRequest", Namespace="", IsNullable=false)]
    public partial class RequestSSLCertRequestType {
    
        private System.DateTime dateTimeField;
    
        private string subscriberEmailAddressField;
    
        private int validityPeriodField;
    
        private bool validityPeriodFieldSpecified;
    
        private CertFieldsType certFieldsField;
    
        private int certificateTypeField;
    
        private string cSRField;
    
        private AccountInfo accountField;
    
        private string serverPlatformField;
    
        private KeyValuePair[] customFieldsField;
    
        private string commentsField;
    
        private bool testField;
    
        private bool testFieldSpecified;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubscriberEmailAddress {
            get {
                return this.subscriberEmailAddressField;
            }
            set {
                this.subscriberEmailAddressField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ValidityPeriod {
            get {
                return this.validityPeriodField;
            }
            set {
                this.validityPeriodField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool ValidityPeriodSpecified {
            get {
                return this.validityPeriodFieldSpecified;
            }
            set {
                this.validityPeriodFieldSpecified = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CertFieldsType CertFields {
            get {
                return this.certFieldsField;
            }
            set {
                this.certFieldsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CertificateType {
            get {
                return this.certificateTypeField;
            }
            set {
                this.certificateTypeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CSR {
            get {
                return this.cSRField;
            }
            set {
                this.cSRField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AccountInfo Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ServerPlatform {
            get {
                return this.serverPlatformField;
            }
            set {
                this.serverPlatformField = value;
            }
        }
    
        /// <remarks/>
        [XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KeyValuePair[] CustomFields {
            get {
                return this.customFieldsField;
            }
            set {
                this.customFieldsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
            }
        }
    
        /// <remarks/>
        [XmlIgnore()]
        public bool TestSpecified {
            get {
                return this.testFieldSpecified;
            }
            set {
                this.testFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CertFieldsType {
    
        private string cnField;
    
        private string oField;
    
        private string[] ouField;
    
        private string sField;
    
        private string cField;
    
        private string eField;
    
        private string lField;
    
        private SANField[] sANField;
    
        private string[] dcField;
    
        private string mSCTIField;
    
        private string mSCTNField;
    
        private string mSAPField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CN {
            get {
                return this.cnField;
            }
            set {
                this.cnField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string O {
            get {
                return this.oField;
            }
            set {
                this.oField = value;
            }
        }
    
        /// <remarks/>
        [XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("Field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] OU {
            get {
                return this.ouField;
            }
            set {
                this.ouField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string S {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string E {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string L {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
    
        /// <remarks/>
        [XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("Field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SANField[] SAN {
            get {
                return this.sANField;
            }
            set {
                this.sANField = value;
            }
        }
    
        /// <remarks/>
        [XmlArray(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItem("Field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] DC {
            get {
                return this.dcField;
            }
            set {
                this.dcField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSCTI {
            get {
                return this.mSCTIField;
            }
            set {
                this.mSCTIField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSCTN {
            get {
                return this.mSCTNField;
            }
            set {
                this.mSCTNField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSAP {
            get {
                return this.mSAPField;
            }
            set {
                this.mSAPField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SANField {
    
        private SANFieldType typeField;
    
        private string valueField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SANFieldType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    public enum SANFieldType {
    
        /// <remarks/>
        DnsName,
    
        /// <remarks/>
        Rfc822Name,
    
        /// <remarks/>
        IPAddress,
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountInfo {
    
        private string nameField;
    
        private string organisationField;
    
        private string organisationGuidField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Organisation {
            get {
                return this.organisationField;
            }
            set {
                this.organisationField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrganisationGuid {
            get {
                return this.organisationGuidField;
            }
            set {
                this.organisationGuidField = value;
            }
        }
    }
}